### ISSUE TITLE
Allow a way to pass raw headers in the Portkey class

### ISSUE THREAD

**Issue by vrushankportkey** [Portkey-AI/portkey-python-sdk#185]
Such a feature may help when providers have specific headers that are use-case specific and don't have wider use beyond that, like Anthropic's `anthropic-beta` header for example - https://x.com/alexalbert__/status/1812921642143900036

**Comment by csgulati09** [comment]
Support for anthropic-beta issue #217 

Can also work on providing extra_headers for majority of the calls
