### ISSUE TITLE
feat: One click observability

### ISSUE THREAD

**Issue by noble-varghese** [Portkey-AI/portkey-python-sdk#43]
In the realm of LLM application development, especially when dealing with your data the ability to observe, troubleshoot, and assess your system is important. Whether you're analyzing the entire system or individual components, this functionality is essential.

With this feature, you can seamlessly fuse the Portkey library with robust observability. Set up a single configuration to setup observability and other features provided by portkey. This makes it easier to incorporate portkey into the existing systems without having to change the implementation.

**Comment by noble-varghese** [comment]
@dosu-bot

**Comment by noble-varghese** [comment]
@dosu-bot

**Comment by devstein** [comment]
@noble-varghese Tell Dosu what you want in the comment. For example, "How do I implement this feature?"

From this issue description Dosu, thinks its help isn't needed because there isn't a clear request

**Comment by noble-varghese** [comment]
@dosu-bot "How do I implement this feature?"
