### ISSUE TITLE
feat: Accept to send the portkey params in the create methods

### ISSUE THREAD

**Issue by noble-varghese** [Portkey-AI/portkey-python-sdk#51]
# Summary
Currently the implementation of the portkey SDK is to create a config and pass the model params on the create methods. This has been useful in most cases but in somecases users want to be able to set the portkey params on the create method over-riding the config created globally. 

**Source**: From the discord conversation with Ragas team.

## Solution
Accepting the portkey params on the create methods of the SDK

**Comment by roh26it** [comment]
This has now been launched in the `1.0.0` SDK. Closing this as done.
