### ISSUE TITLE
Does ChatCompletions.create support OpenAI function calling?

### ISSUE THREAD

**Issue by nerdai** [Portkey-AI/portkey-python-sdk#57]
Hey,

I'm looking to updated our the portkey integration within LlamaIndex lib. Specifically looking to use v1 openai interface for function calling with portkey. 

- When I try to use regular `chat` (which invokes portkey.ChatCompletions.create) I can pass kwargs `tools` and `tool_choice` but what I get back is a response that doesn't appear to use the tools at all
- When I try to use stream mode, I get thrown a `ValidationError` because of the added `tools` and `tool_choice` args.

Reference:
https://platform.openai.com/docs/api-reference/chat/create

**Comment by noble-varghese** [comment]
Hello @nerdai,
We're currently investigating this. Incorporating the latest OpenAI-based updates into the package is necessary to resolve this. We're planning to release a new version of the package by the end of this week or early next week, at which point this issue should be addressed. Thank you for bringing it to our attention.

**Comment by VisargD** [comment]
Apologies for not updating this thread on time. This was released and can be used in the latest version of this SDK. Please reopen the issue or create a new one if you face any other issues.
