### ISSUE TITLE
pydantic dependency is causing conflicts with other packages

### ISSUE THREAD

**Issue by jKlag** [Portkey-AI/portkey-python-sdk#60]
### Contact Details

josh@ensis.ai

### What happened?

This SDK's dependency on an exact version of pydantic (`pydantic==1.10.12`) is causing dependency conflicts with some other packages, in my case `django-ninja` (depends on pydantic<3.0.0 and >=2.0)

If it's all possible to loosen the package's range of acceptable `pydantic` versions, I think it may be worth doing so to allow developers to use this SDK alongside a wider range of other packages.

### Version

0.1.xx (Default)

### Relevant log output

```shell
portkey-ai 0.1.27 depends on pydantic==1.10.12
django-ninja 1.0.1 depends on pydantic<3.0.0 and >=2.0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ayush-portkey** [comment]
Hi @jKlag,

Thank you for raising this issue. Team is working on adding support for newer pydantic versions.
I'll update you very soon.

**Comment by kobibarhanin** [comment]
Waiting for this as well
