### ISSUE TITLE
too strict typing_extensions dependency

### ISSUE THREAD

**Issue by MrZoidberg** [Portkey-AI/portkey-python-sdk#66]
### Contact Details

mihail.merkulov@gmail.com

### What happened?

I'm using portkey-ai package along with langchain and chroma. chroma cannot work with `typing-extensions<4.8.0`, but portkey-ai package has strict dependency on `typing-extensions==4.7.1`

Is it possible to support a wider range of versions for typing-extensions?

### Version

0.1.xx (Default)

### Relevant log output

```shell
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
portkey-ai 1.1.1 requires typing-extensions==4.7.1, but you have typing-extensions 4.8.0 which is incompatible.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by VisargD** [comment]
Hey @MrZoidberg. Thanks for reporting this issue. I will remove the strict dependency and run the tests to verify if anything else breaks due to it.

**Comment by VisargD** [comment]
@MrZoidberg - We have pushed a new version (1.1.2) which supports typing dependencies >=4.7.1,<5.0 . This should solve your dependency conflict. Thanks for reporting the issue. Please open a new issue if you find some other bugs.

Release link:https://github.com/Portkey-AI/portkey-python-sdk/releases/tag/v.1.1.2
